Repository modern-agile-team/9term-main-back, pull requests merged in 2025-07, with the labels that each got.

#47 docs: (#45) 댓글 API Swagger 문서화
  src/auth/auth.service.ts
  src/comments/comment.swagger.ts
  src/comments/comments.controller.ts
  src/comments/dto/api-response.dto.ts
  src/comments/dto/create-comment.dto.ts
  src/comments/dto/query-comment.dto.ts
  src/comments/dto/res-comment.dto.ts
  src/comments/dto/update-comment.dto.ts
  src/main.ts
  src/posts/post.swagger.ts
  src/posts/posts.controller.ts
Labels: 📚 Docs

#60 fix: (#59) CI/CD 설정에 .env 파일 추가
  .github/workflows/main.yml
Labels: 🚀 infra

#55 refactor: (#53) Comment API에 DTO 및 인터페이스 적용
  src/comments/comment.swagger.ts
  src/comments/comments.controller.ts
  src/comments/comments.module.ts
  src/comments/comments.repository.ts
  src/comments/comments.service.ts
  src/comments/dto/requests/create-comment.dto.ts
  src/comments/dto/requests/query-comment.dto.ts
  src/comments/dto/requests/update-comment.dto.ts
  src/comments/dto/responses/api-response.dto.ts
  src/comments/dto/responses/res-comment.dto.ts
  src/comments/dto/user-info.dto.ts
  src/comments/interfaces/comments.repository.interface.ts
  src/comments/interfaces/comments.service.interface.ts
  src/posts/posts.module.ts
  src/posts/posts.service.ts
Labels: 🔨 Refactor

#71 refactor: (#70) ApiResponseDto 파일 통합 및 공통 경로 적용
  src/comments/comment.swagger.ts
  src/comments/comments.controller.ts
  src/comments/dto/responses/api-response.dto.ts
  src/common/dto/api-response.dto.ts
  src/groups/group.swagger.ts
  src/posts/dto/responses/api-response.dto.ts
  src/posts/post.swagger.ts
  src/posts/posts.controller.ts
Labels: 🔨 Refactor

#67 feat: (#57) S3 이미지 업로드, 삭제 기능 추가
  package-lock.json
  package.json
  prisma/migrations/20250723023212_post_schema_update/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/app.module.ts
  src/groups/groups.controller.ts
  src/posts/dto/responses/post-response.dto.ts
  src/posts/dto/responses/post-write-response.dto.ts
  src/posts/interfaces/post.interface.ts
  src/posts/posts.repository.ts
  src/posts/posts.service.ts
  src/s3/dto/upload-image-response.dto.ts
  src/s3/s3.module.ts
  src/s3/s3.service.ts
  src/s3/s3.types.ts
Labels: ✨ Feature
