Repository modern-agile-team/9term-main-back, pull requests merged in 2025-08, with the labels that each got.

#79 feat: (#77) 그룹 이미지 관련 S3를 통한 이미지 업로드 및 삭제 추가
  package-lock.json
  prisma/migrations/20250730070646_add_group_enums_and_img_path/migration.sql
  prisma/schema.prisma
  src/groups/dto/create-group-image.dto.ts
  src/groups/dto/group-join-status.dto.ts
  src/groups/dto/group-with-member-count.dto.ts
  src/groups/groups.controller.ts
  src/groups/groups.module.ts
  src/groups/groups.repository.ts
  src/groups/groups.service.ts
  src/groups/types/group-inputs.ts
Labels: ✨ Feature

#92 refactor: (#81) Auth 모듈에서 Users 도메인 분리 및 서비스 구조 개선
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/auth.swagger.ts
  src/auth/dto/auth-response.dto.ts
  src/auth/dto/requests/login-request.dto.ts
  src/auth/dto/requests/signup-request.dto.ts
  src/auth/dto/responses/auth-response.dto.ts
  src/auth/dto/responses/login-response.dto.ts
  src/auth/strategies/access.strategy.ts
  src/auth/strategies/refresh.strategy.ts
  src/auth/user.controller.ts
  src/auth/user.dto.ts
  src/auth/user.repository.ts
  src/common/dto/api-response.dto.ts
  src/users/dto/reponses/user-profile.dto.ts
  src/users/interfaces/users.interface.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: 🔨 Refactor

#97 feat: (#96) s3 구조 변경
  src/groups/groups.repository.ts
  src/groups/groups.service.ts
  src/posts/interfaces/post.interface.ts
  src/posts/posts.repository.ts
  src/posts/posts.service.ts
  src/s3/s3.service.ts
  src/s3/s3.types.ts
Labels: ✨ Feature

#100 feat: (#82) 멤버 역할 변경 기능 추가 및 관련 API 구현
  src/member/dto/update-member-role.dto.ts
  src/member/member.controller.ts
  src/member/member.repository.ts
  src/member/member.service.ts
  src/member/member.swagger.ts
Labels: ✨ Feature

#114 feat: (#112) Post에 profileImageUrl 필드 추가
  src/posts/dto/responses/post-write-response.dto.ts
  src/posts/dto/user-info.dto.ts
  src/posts/interfaces/post.interface.ts
  src/posts/posts.repository.ts
  src/posts/posts.service.ts
Labels: ✨ Feature

#116 refactor: (#115) UsersService 로직 및 인터페이스 정리
  src/auth/auth.service.ts
  src/users/dto/responses/user-profile.dto.ts
  src/users/interfaces/users.interface.ts
  src/users/users.controller.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: 🔨 Refactor

#113 feat: (#109) 내 그룹 목록 조회 기능 추가
  src/auth/auth.service.ts
  src/users/dto/responses/user-group-summary.dto.ts
  src/users/users.controller.ts
  src/users/users.repository.ts
  src/users/users.service.ts
  src/users/users.swagger.ts
Labels: ✨ Feature

#124 fix: (#123)존재하지 않는 그룹 조회 시 404 에러 응답 추가
  src/posts/posts.module.ts
  src/posts/posts.service.ts
Labels: 🐞 BugFix

#126 feat: (#125) GroupMemberGuard 적용으로 작성/수정/삭제 제한
  src/comments/comment.swagger.ts
  src/comments/comments.controller.ts
  src/comments/comments.module.ts
Labels: ✨ Feature

#128 feat: (#127) 멤버 목록에 LEFT 필터링 적용
  src/member/member.repository.ts
Labels: ✨ Feature
