Repository modern-agile-team/9term-main-back, pull requests merged in 2025-09, with the labels that each got.

#132 feat: (#129) 그룹 가입 신청 알림 구현
  package-lock.json
  package.json
  prisma/migrations/20250819035016_add_notification_model/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/member/member.module.ts
  src/member/member.repository.ts
  src/member/member.service.ts
  src/notifications/notifications.controller.ts
  src/notifications/notifications.mapper.ts
  src/notifications/notifications.module.ts
  src/notifications/notifications.repository.ts
  src/notifications/notifications.service.ts
  src/notifications/types/notification-response.type.ts
  src/notifications/types/notification-signal.type.ts
  src/users/users.module.ts
Labels: ✨ Feature

#138 chore: (#137) Prisma 마이그레이션 스텝 추가
  .github/workflows/main.yml
Labels: 🚀 infra

#136 feat: (#134) 모집 상태 업데이트 엔드포인트 추가
  prisma/migrations/20250906181432_group_recruit_status_enum_and_default/migration.sql
  prisma/migrations/20250910064717_rename_enum_values/migration.sql
  prisma/schema.prisma
  src/groups/dto/group-with-member-count.dto.ts
  src/groups/dto/update-recruit.dto.ts
  src/groups/group.swagger.ts
  src/groups/groups.controller.ts
  src/groups/groups.service.ts
  src/groups/types/group-inputs.ts
Labels: ✨ Feature

#145 feat: (#142) 알림 응답 DTO 및 Swagger 문서 추가
  src/notifications/dto/notification-response.dto.ts
  src/notifications/notifications.controller.ts
  src/notifications/notifications.mapper.ts
  src/notifications/notifications.service.ts
  src/notifications/notifications.swagger.ts
  src/notifications/types/notification-response.type.ts
Labels: 📚 Docs
