Repository modern-agile-team/9term-main-back, pull requests merged in 2025-04, with the labels that each got.

#4 npm을 통한 Swagger설치 및 기초설정
  .gitignore
  .prettierrc
  README copy.md
  eslint.config.mjs
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: ✨ Feature

#6 Feat/#5/prisma mvp db
  .github/CODEOWNERS
  .gitignore
  .prettierrc
  eslint.config.mjs
  nest-cli.json
  package-lock.json
  package.json
  prisma/migrations/20250403051544_init_mvp/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: ✨ Feature

#7 [Chore] main 브랜치 develop 동기화
  package-lock.json
  package.json
  prisma/migrations/20250403051544_init_mvp/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: ⚙ Setting

#9 refactor: (#8) 데이터베이스 스키마 및 마이그레이션 파일 리팩토링
  package-lock.json
  package.json
  prisma/migrations/20250403051544_init_mvp/migration.sql
  prisma/migrations/20250410091626_mvp_init/migration.sql
  prisma/schema.prisma
Labels: 🔨 Refactor
